name: Berean Sermon Search Engine

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      github_token: ${{ secrets.GITHUB }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Adjust the version as needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Script
        run: python get_data.py